### PR TITLE
except fixer: Make sure to actually check against the value of a node Fixes #42

### LINKED ISSUE #42: Fix PR #40 (except fixer: don't do anything if the "as" is already there) by checking against value of node
### Description

My fix PR #40 didn't actually do anything. I must have dropped the `.value` during some refactoring.

Luckily this doesn't cause any regression.

### PR DESCRIPTION
**Pull request by dgrant**
### Description

In the except fixer, in PR #40 I tried to make it not think a change was made when there really was no change made. This didn't actually work, as I somehow didn't compare with the `.value` of the node, probably due to me dropping it during refactoring.

Fixes: #42

### CODE REVIEW

**Comment by dgrant** [comment]
Can this be merged and a new fissix release created? Right now I'm installing git+https://github.com/dgrant/fissix.git@d5537fd6165de9d2ced3e1de378a7ec83a7bd50d#fissix and that takes forever as it does a git clone of fissix, which does a git submodule clone of cpython which takes forever for me. This happens once in a while when I update my Docker image.

**Comment by dgrant** [comment]
Can this be merged?

**Comment by jreese** [comment]
Sorry for missing this, I'll get a release cut soon.

**Comment by jreese** [comment]
v21.11.13 should be available from pypi now.

**Pull request merged**
